server:
  port: ${DISCOVERY_SERVER_PORT}

spring:
  application:
    name: pm-discovery-server
  main:
    banner-mode: off

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    response-cache-update-interval-ms: 5000

logging:
  file:
    name: logs\discovery-server.log